settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: /Users/davidvanisacker/Programming/Go/src/github.com/Proofsuite/amp-matching-engine
  path: /Users/davidvanisacker/Programming/Go/src/github.com/Proofsuite/amp-matching-engine
  commands:
    clean:
      status: true
    vet:
      status: true
    fmt:
      status: true
    test:
      status: true
    generate:
      status: true
    install:
      status: true
    build:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
  pattern: "n"
